services:
  api:
    # Development-specific overrides
    environment:
      # More verbose logging for development
      LOG_LEVEL: DEBUG
      # Enable hot reload
      PYTHONPATH: /app/src
    volumes:
      # Mount source for hot reload
      - ${PWD}/src:/app/src:ro
      - ${PWD}/tests:/app/tests:ro
      - ${PWD}/experiments:/app/experiments
      - ${PWD}/scenarios:/app/scenarios:ro
      # Development tools
      - ${PWD}/.git:/app/.git:ro
    # Development command with hot reload
    command: ["uv", "run", "uvicorn", "src.glitch_core.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  qdrant:
    # Development-specific Qdrant settings
    environment:
      QDRANT__STORAGE__OPTIMIZERS__DELETED_THRESHOLD: 0.5  # Less aggressive for dev
      QDRANT__STORAGE__OPTIMIZERS__VACUUM_MIN_VECTOR_NUMBER: 100  # Lower threshold for dev

  redis:
    # Development-specific Redis settings
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  ollama:
    # Development-specific Ollama settings
    environment:
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_MAX_LOADED_MODELS: 1
      OLLAMA_KEEP_ALIVE: 1h  # Shorter for development 