global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Glitch API
  - job_name: 'glitch-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Qdrant
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']
  #   scrape_interval: 30s

  # Node exporter (if monitoring host metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 30s 