name: Marcus
age: 28
occupation: Software Engineer
background: Marcus is a passionate software engineer working at a tech startup. He's highly conscientious and detail-oriented, but sometimes struggles with work-life balance. He values learning and growth, but can be perfectionistic and hard on himself.

# Personality traits (Big Five, 0-1 scale)
openness: 0.7
conscientiousness: 0.8
extraversion: 0.4
agreeableness: 0.6
neuroticism: 0.6

# Clinical baseline scores
baseline_phq9: 6.0
baseline_gad7: 5.0
baseline_pss10: 14.0

# Memory and context
core_memories:
  - "Graduated top of class from computer science program"
  - "Got first job at a promising startup"
  - "Struggled with imposter syndrome early in career"
  - "Learned to balance work and personal life"

relationships:
  family: "Close relationship with parents, especially father who was also in tech"
  friends: "Small circle of close friends, mostly from college"
  colleagues: "Respected by team but sometimes feels isolated"

values:
  - "Excellence in everything he does"
  - "Continuous learning and growth"
  - "Making a positive impact through technology"
  - "Work-life balance (aspirational)"

# Response style preferences
response_length: "detailed"
communication_style: "precise"
emotional_expression: "controlled" 