age: 30
agreeableness: 0.8
background: A test persona for Phase 3 validation.
baseline_gad7: 3.0
baseline_phq9: 4.0
baseline_pss10: 10.0
communication_style: balanced
conscientiousness: 0.7
core_memories:
- Graduated from university with honors
- Started first job in tech industry
emotional_expression: moderate
extraversion: 0.5
name: Test Persona
neuroticism: 0.3
occupation: Software Engineer
openness: 0.6
relationships:
  family: Close relationship with parents
  friends: Small but close circle of friends
response_length: medium
values:
- Hard work and dedication
- Continuous learning
